support for audit logs
kubesphere/fluentbit-operator pull request #45
Opened 2021-04-02 07:02 UTC by zhu733756

/kind feature

2021-04-02 07:26 UTC, wanjunlei commented
You can add a doc to Introduce how to use `auditd`, and collect audit logs with fluentbit-operator.

2021-04-08 06:53 UTC, benjaminhuo commented on README.md
> +green open ks-auditd-logs-2021.04.06 QeI-k_LoQZ2h1z23F3XiHg  5 1 404879 0 298.4mb 149.2mb
still `ks-auditd-logs-`

2021-04-08 06:54 UTC, benjaminhuo requested changes
`ks-auditd-logs-` should be modified too

2021-04-08 07:10 UTC, zhu733756 commented on README.md
> +green open ks-auditd-logs-2021.04.06 QeI-k_LoQZ2h1z23F3XiHg  5 1 404879 0 298.4mb 149.2mb
fixed

2021-04-08 07:13 UTC, benjaminhuo approved these changes
/lgtm
@wanjunlei pls review this PR, and possibly we need to release FB operator v0.4.1

2021-04-08 07:13 UTC, benjaminhuo commented
/assign @wanjunlei

2021-04-08 08:15 UTC, wanjunlei approved these changes

2021-04-08 08:32 UTC, merged